### ISSUE TITLE
Missing Salt master config

### ISSUE THREAD

**Issue by tracphil** [edvinasme/salt-master#1]
Nice layout. I like it. Just an FYI that you are missing  the salt master config as referenced in your README https://github.com/edvinasme/salt-master/blob/master/config/master

**Comment by edvinasme** [comment]
I have pushed the updated config in https://github.com/edvinasme/salt-master/commit/bdf4822365ca32092d17b403937cba4d71fd1c27

Additionally, there was a fix in example minion config (typo) in https://github.com/edvinasme/salt-master/commit/a9a7b7e120855b8841cb8aca51c3da97e82a2d2b so you might want to update your repository.

Thanks for report. Closing.
